export const GET_SHIPMENTS = 'GET_SHIPMENTS';
export const GET_SHIPMENTS_SUCCESS = 'GET_SHIPMENTS_SUCCESS';
export const GET_SHIPMENTS_ERROR = 'GET_SHIPMENTS_ERROR';
export const SELECT_SHIPMENT = 'SELECT_SHIPMENT';
