export const UPDATE_SHIPMENT_NAME = 'UPDATE_SHIPMENT_NAME';
export const UPDATE_SHIPMENT_NAME_SUCCESS = 'UPDATE_SHIPMENT_NAME_SUCCESS';
export const UPDATE_SHIPMENT_NAME_ERROR = 'UPDATE_SHIPMENT_NAME_ERROR';
